### ISSUE TITLE
Replace gometalinter / Fix TracisCI

### ISSUE THREAD

**Issue by tastypackets** [kubernetes-sigs/cli-experimental#120]
Looks like all TravisCI PRs are failing: https://travis-ci.org/github/kubernetes-sigs/cli-experimental/pull_requests

`build gopkg.in/alecthomas/gometalinter.v2: cannot load github.com/nicksnyder/go-i18n/i18n: cannot find module providing package github.com/nicksnyder/go-i18n/i18n`

`gometalinter` manifest import path is now invalid with `go-i18n` repo having a `v2` directory: https://github.com/alecthomas/gometalinter/blob/master/vendor/manifest#L21

However gometalinter was deprecated [2019-04-07](https://github.com/alecthomas/gometalinter/issues/590), so it should probably be replaced in this project.

**Comment by natasha41575** [comment]
I believe this issue can be closed now (see #147)
