### ISSUE TITLE
kustomize docs for Guides > Introduction don't show full example

### ISSUE THREAD

**Issue by mattwelke** [kubernetes-sigs/cli-experimental#143]
I started reading about kustomize today, so I was following this page (https://kubectl.docs.kubernetes.io/guides/introduction/kustomize/). I don't see anything called quickstart on the left menu so I assumed this was the page to follow and run commands alongside to see it in action. Step 1 says "Make a kustomization file" and it shows a file structure:

```
~/someApp
├── deployment.yaml
├── kustomization.yaml
└── service.yaml
```

I grabbed the example NGINX deployment from the k8s docs and made my own deployment file. I skipped service.

Below, it says to run `kustomize build ~/someApp`, without providing an example kustomization.yaml file, so I assumed it would work without that file or with an empty file of that name and have some default behavior, so I ran `kustomize build` since I was working in the directory for my example already. No output, but no errors. I also tried `kustomize build .` in case I had to explicitly specify the directory to build (like the command in the docs). Same thing.

I think the docs should be improved. I can't find anywhere to actually get started. The "Examples" page doesn't seem to be somewhere I can go to get the kuztomization.yaml file I need to complete the quickstart because it's just a page displaying two links (Multibase and Inline Patch) and I don't know what those things mean yet. I don't know which one to click.

**Comment by mattwelke** [comment]
/remove-lifecycle-stale

Introduction guide still lacks example kustomization.yaml file.

**Comment by tehleet** [comment]
yes, files would be great, I also found this https://github.com/kubernetes-sigs/kustomize#1-make-a-kustomization-file
