### ISSUE TITLE
It is too hard to find out how customization works.

### ISSUE THREAD

**Issue by abentley** [kubernetes-sigs/cli-experimental#224]
https://kubectl.docs.kubernetes.io/guides/introduction/kustomize/ says what files are needed, but not what should be in those files, which is what I came to the document to find out.

**Comment by Dirc** [comment]
That is exactly what I was missing aswell. 

I was expecting a little getting started guide with something like this:

- run kustomize create
- add `resources` to your `kustomize.yaml`
- maybe add labels (or another simple addon)
- run kustomize build
- check result

And I would expect it under "introduction".
