### ISSUE TITLE
Site edit button goes to the wrong location

### ISSUE THREAD

**Issue by rothgar** [kubernetes-sigs/cli-experimental#26]
I tried editing a page by clicking "Edit this page" from the rendered website and it brought me to

`https://github.com/kubernetes-sigs/cli-experimental/edit/master/content/en/installation/krew/bash_zsh.md`

But the real path is

`https://github.com/kubernetes-sigs/cli-experimental/blob/master/site/content/en/installation/krew/bash_zsh.md`

I didn't track down where that button is in the template so I wanted to open a quick issue to track it.

**Comment by pwittrock** [comment]
Fixed
