### ISSUE TITLE
Install via homebrew for macOS or Linux

### ISSUE THREAD

**Issue by rothgar** [kubernetes-sigs/cli-experimental#28]
Homebrew installs are supported on macOS and Linux. We should maybe separate the homebrew and macports install sections and let people running linux know that homebrew work there too.

This applies to kubectl and kustomize

**Comment by balibebas** [comment]
I think people running Linux known homebrew works there—they just don't care. I preferred to see MacPorts and Homebrew right next to each other. Because Homebrew is meh so it's always nice to be reminded there's a second package manager.

**Comment by rothgar** [comment]
I'm not sure I agree. The past 3 repos I've submitted homebrew support to didn't know it worked on Linux. I also regularly (almost weekly) get people mention to me online that they didn't know homebrew worked on linux.

I think it would be worth pointing out for people looking to install the tools on linux that they can use homebrew if they would like.

**Comment by balibebas** [comment]
It sounds like you work with Homebrew a lot on Linux so I understand your experiences are different. All major Linux distros ship with an integrated package manager. Adding info about Homebrew availability on Linux/WSL leads to choice paralysis and is something I suspect few Linux users who don't know Homebrew works there would benefit from.
