### ISSUE TITLE
Emojis (heavy_check_mark) not rendering

### ISSUE THREAD

**Issue by CorwinNewall** [kubernetes-sigs/cli-experimental#304]
**To reproduce:**
See the “Field Descriptions” subsection of https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/

**Expected behaviour:**
For required fields I expect to see ✔️ in the _Required_ column

**Actual behaviour**
I see literally `:heavy_check_mark:`

**System:**
macOS Monterey 12.6.1
both browsers
- Chrome Version 107.0.5304.121 (Official Build) (x86_64)
- Edge Version 108.0.1462.41 (Official build) (x86_64)

**Screenshot**
<img width="923" alt="image" src="https://user-images.githubusercontent.com/25069619/205779170-2c2928d9-ef5b-46d8-b0ad-cd9ccfae9895.png">

**Comment by Aisuko** [comment]
remove
