### ISSUE TITLE
kustomize typo

### ISSUE THREAD

**Issue by Sapp00** [kubernetes-sigs/cli-experimental#308]
In the docs, there is a typo in the example at the very bottom.

Link: https://kubectl.docs.kubernetes.io/references/kustomize/builtins/

> ```
> apiVersion: builtin
> kind: HelmChartInflationGenerator
> metadata:
>   name: myMap
> name: minecraft
> repo: https://kubernetes-charts.storage.googleapis.com
> version: v1.2.0
> releaseName: test
> namespace: testNamespace
> valuesFile: values.yaml
> IncludeCRDs: true

It should be 

`includeCRDs: true`

**Comment by Aisuko** [comment]
Thank you, we will do a PR solve this.
