### ISSUE TITLE
What are the contents of those files in the docu?

### ISSUE THREAD

**Issue by bumarcell** [kubernetes-sigs/cli-experimental#315]
https://kubectl.docs.kubernetes.io/guides/introduction/kustomize/

**Comment by Aisuko** [comment]
Hi, What do you mean? If you are looking for the code file, you can just search the keywords in the whole project and then. It will goog to go.

**Comment by bumarcell** [comment]
I just didn't find it that trivial to find those files (was in the docu page and not on git)

**Comment by Aisuko** [comment]
I see. We plan to a new version document maybe it is a little bit better.
