### ISSUE TITLE
Go Source

### ISSUE THREAD

**Issue by david-thrower** [kubernetes-sigs/cli-experimental#318]
On page: https://kubectl.docs.kubernetes.io/installation/kustomize/source/

Git version 2.30.2 rejects the command to clone the repo with the error caption. 

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
Suggested fix:

replace:

`git clone git@github.com:kubernetes-sigs/kustomize.git`

with:

`git clone https://git@github.com/kubernetes-sigs/kustomize.git`

**Comment by Aisuko** [comment]
Thank you, we will fix this issue.
