### ISSUE TITLE
Please add documentation to kustomize commands, just a few short examples would be nice.

### ISSUE THREAD

**Issue by ravn** [kubernetes-sigs/cli-experimental#319]
"kustomize cfg" is very terse, and doesn't help me as a learner.  This most likely applies to other pages as well.

It would be nice if there was a few examples with an explanation of what they do, plus a link to the full help text for the command in question.

**Comment by Aisuko** [comment]
Thanks for your feedback. If there is any issue, we will fix it as soon as we can.
