### ISSUE TITLE
I can't find documents for old releases

### ISSUE THREAD

**Issue by unclok** [kubernetes-sigs/cli-experimental#326]
Hello,

I've tried to add labels into `spec/template/metadata/labels` this time.

I've found [this document](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels/) and I tried the flag `includeTemplates` like the document said, but I found out that this flag doesn't exist in my version of kubectl (v1.23.5).

I couldn't find any other option from the official document, so I had to find other blogs to find a way to use label-transformer.

Because kubernetes provides new release every 3 months and sometimes it brings a lot of changes, I think kustomize documentation also need to provide various versions, like kubernetes official documentation.

**Comment by Aisuko** [comment]
Thanks for your feedback. We can open an issue to request a new feature after we discussed it with the maintainers.

**Comment by natachasouza** [comment]
I just went through the same issue and tried to find the Kustomize documentation for an older version, but couldn't. The problem is not finding out my kustomize version, is to find documentation specific for that version. In this case, there is a new field that was added in a newer version.
