### ISSUE TITLE
curl doesn't work

### ISSUE THREAD

**Issue by mvm-sp** [kubernetes-sigs/cli-experimental#328]
Executing curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash nothing happen

**Comment by mvm-sp** [comment]
I saw there´s an error related to ssl then adding --insecure works for me

`curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" --insecure | bash `

**Comment by Aisuko** [comment]
Thanks for your feedback, we can update the command with `--insecure` command to make the command work for everyone.
