### ISSUE TITLE
Multinamespace url returnig 404

### ISSUE THREAD

**Issue by luis-giraldo** [kubernetes-sigs/cli-experimental#332]
The [multi-namespaces](https://kubectl.docs.kubernetes.io/guides/example/multi_base/multi-namespace.md). link returning 404

This is the source, at the bottom, the multinamespace link

https://github.com/kubernetes-sigs/cli-experimental/blob/master/site/content/en/guides/example/multi_base.md

**Comment by Aisuko** [comment]
Thanks for your feedback, this will be fixed after other PRs get merged.
