### ISSUE TITLE
Provide example Kustomize file

### ISSUE THREAD

**Issue by MonicaG** [kubernetes-sigs/cli-experimental#365]
In the [Introduction to Kustomize](https://kubectl.docs.kubernetes.io/guides/introduction/kustomize/) guide, it would be helpful if the [Make a kustomization file](https://kubectl.docs.kubernetes.io/guides/introduction/kustomize/#1-make-a-kustomization-file) section provided an example of the Kustomize file to create. 

Currently, it just says to make the file. As someone brand new to the project, it would help to have an example of the Kustomize file in this section.

**Comment by niclan** [comment]
Ditto here.  In https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/ there are examples about configMapGenerators but it is very unclear how I change simple attributes, like the namespace, in a set of manifests.
