### ISSUE TITLE
Reference/docs make no mention of kubectl/Kustomize divergence

### ISSUE THREAD

**Issue by holmesmr** [kubernetes-sigs/cli-experimental#57]
The reference documentation for the Kustomize tool is for Kustomize 3.0, which is not supported in any production version of kubectl to date, and neither the Kustomize reference nor the kubectl reference for `kubectl kustomize` make any reference to this divergence, what version was included in kubectl, or which versions several directives were added in.

**Comment by holmesmr** [comment]
Given this has been open for close to 3 months with no acknowledgement, I'll consider this to mean this is a WONTFIX.

**Comment by sftim** [comment]
BTW https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/ makes some mention of the difference
