### ISSUE TITLE
kustomize doesn't explain what to do

### ISSUE THREAD

**Issue by rvandegrift** [kubernetes-sigs/cli-experimental#80]
The introduction at [1] shows some possible directory structures for using kustomize.  It contains the steps "Make a kustomization file" and "Create variants using overlays" but does not explain how to do these.  There are no links to other docs indicating what my next steps should be to figure out how to accomplish these tasks.

[1] - https://kubectl.docs.kubernetes.io/guides/introduction/kustomize/#1-make-a-kustomization-file

**Comment by nathanl** [comment]
Related: https://github.com/kubernetes-sigs/cli-experimental/issues/78
